-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\acs_cranecontroller_firsttest\acs_crane_ip_dut.vhd
-- Created: 2019-10-25 14:34:13
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: acs_crane_ip_dut
-- Source Path: acs_crane_ip/acs_crane_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY acs_crane_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        destination_x                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En15
        desired_angle                     :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
        position                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En15
        angle                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
        ce_out                            :   OUT   std_logic;  -- ufix1
        pwm                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En2
        );
END acs_crane_ip_dut;


ARCHITECTURE rtl OF acs_crane_ip_dut IS

  -- Component Declarations
  COMPONENT acs_crane_ip_src_Subsystem1
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          destination_x                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En15
          desired_angle                   :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
          position                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En15
          angle                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
          ce_out                          :   OUT   std_logic;  -- ufix1
          pwm                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En2
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : acs_crane_ip_src_Subsystem1
    USE ENTITY work.acs_crane_ip_src_Subsystem1(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL pwm_sig                          : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_acs_crane_ip_src_Subsystem1 : acs_crane_ip_src_Subsystem1
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              destination_x => destination_x,  -- ufix32_En15
              desired_angle => desired_angle,  -- ufix16_En15
              position => position,  -- ufix32_En15
              angle => angle,  -- ufix16_En15
              ce_out => ce_out_sig,  -- ufix1
              pwm => pwm_sig  -- ufix16_En2
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  pwm <= pwm_sig;

END rtl;

