# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EAAES/Portal-Crane/Miniproject_motor_control.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1_1/Block_design_xbar_1.xci
# IP: The module: 'Block_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EAAES/Portal-Crane/Miniproject_motor_control.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1_1/Block_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/EAAES/Portal-Crane/Miniproject_motor_control.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1_1/Block_design_xbar_1.xci
# IP: The module: 'Block_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EAAES/Portal-Crane/Miniproject_motor_control.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1_1/Block_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
