webtalk_init -webtalk_dir D:\\EAAES\\Portal-Crane\\Miniproject_motor_control.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-29 21:07:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ivqhvpual9s8brdhuv7ie5v6gv" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_46" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.053 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1572363622931" -context "sdk\\\\bsp/1572363622931"
webtalk_add_data -client sdk -key hwid -value "1572257252848" -context "sdk\\\\bsp/1572363622931"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1572363622931"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1572363622931"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1572363622931"
webtalk_add_data -client sdk -key uid -value "1572366202799" -context "sdk\\\\bsp/1572366202799"
webtalk_add_data -client sdk -key hwid -value "1572257252848" -context "sdk\\\\bsp/1572366202799"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1572366202799"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1572366202799"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1572366202799"
webtalk_add_data -client sdk -key uid -value "1572367608261" -context "sdk\\\\bsp/1572367608261"
webtalk_add_data -client sdk -key hwid -value "1572257252848" -context "sdk\\\\bsp/1572367608261"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1572367608261"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1572367608261"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1572367608261"
webtalk_add_data -client sdk -key uid -value "1572368977287" -context "sdk\\\\bsp/1572368977287"
webtalk_add_data -client sdk -key hwid -value "1572257252848" -context "sdk\\\\bsp/1572368977287"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1572368977287"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1572368977287"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1572368977287"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key DebugCount -value "140" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1572379677329"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1572379677329"
webtalk_transmit -clientid 459308771 -regid "" -xml D:\\EAAES\\Portal-Crane\\Miniproject_motor_control.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\EAAES\\Portal-Crane\\Miniproject_motor_control.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\EAAES\\Portal-Crane\\Miniproject_motor_control.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
